KeyFile: slim down
elementary/switchboard-plug-applications pull request #138
Opened 2020-10-27 22:16 UTC by danrabbit

Almost none of these setters are used outside of the commandline constructor, so we can simplify this a ton

2020-11-07 17:15 UTC, tintou requested changes

2020-11-07 17:15 UTC, tintou commented on src/Startup/Backend/KeyFile.vala
> +            icon = keyfile_get_string (KeyFileDesktop.KEY_ICON),
It is technically
```suggestion
            icon = keyfile_get_locale_string (KeyFileDesktop.KEY_ICON),
```

2020-11-07 17:15 UTC, tintou commented on src/Startup/Backend/KeyFile.vala
> +            return keyfile_get_string (KEY_ACTIVE) == "true";
```suggestion
            return keyfile.get_boolean (KeyFileDesktop.GROUP, KEY_ACTIVE);
```

2020-11-07 17:15 UTC, tintou commented on src/Startup/Backend/KeyFile.vala
> +            keyfile.set_string (KeyFileDesktop.GROUP, KEY_ACTIVE, as_string);
```suggestion
            keyfile.set_boolean (KeyFileDesktop.GROUP, KEY_ACTIVE, value);
```

2020-12-02 17:15 UTC, jeremypw approved these changes
No regression found so I guess this code is not needed.

2020-12-02 18:17 UTC, merged