Spelling: Home, in it, Bluetooth
elementary/switchboard-plug-applications pull request #150
Opened 2021-02-13 11:40 UTC by comradekingu

2021-02-15 20:24 UTC, cassidyjames commented on src/Permissions/Widgets/AppSettingsView.vala
> +            _("Access your entire Home folder, including any hidden folders in it."),
Not sure the last part is needed as it's implied, and sounds awkward to me when including it.

```suggestion
            _("Access your entire Home folder, including any hidden folders."),
```

2021-02-15 20:26 UTC, cassidyjames requested changes
Generally it's better to propose these as their own PRs so unrelated changes aren't held up in case there is discussion about a different change.

For this specifically, the capitalization makes sense to me, but I don't think we need to add "in it" to the Home label; it's implied, and seems like unnecessary wordiness.

2021-02-15 20:26 UTC, cassidyjames commented on src/Permissions/Widgets/AppSettingsView.vala
> +            _("Manage Bluetooth devices including pairing, unpairing, and discovery."),
:+1:

2021-04-07 18:52 UTC, jeremypw commented
I agree that the words "in it" are superfluous after "including ..."

2021-04-07 18:53 UTC, jeremypw commented
@comradekingu Are you able to update this PR?

2021-04-07 20:33 UTC, danrabbit approved these changes

2021-04-07 20:36 UTC, merged